# generated_strategy.py — auto-generated by agent.py, do not hand-edit.
# Run it from the project root so `data_engine` and `engine` are importable.
"""
Entry rule: row['close'] > row['sma_20']
Exit rule:  not (row['close'] > row['sma_20'])
"""
from data_engine import fetch_historical_data
from engine.backtest import run_backtest
from engine.conditions import Condition, ConditionGroup, Rule
from engine.metrics import compute_metrics

stock = input("Enter stock ticker (e.g., AAPL, NVDA, SPY): ").strip().upper()
from_date = input("Enter start date (YYYY-MM-DD): ").strip()
to_date = input("Enter end date (YYYY-MM-DD): ").strip()
timeframe = input("Enter timeframe (e.g., 1d for daily, 1h for hourly): ").strip()

INITIAL_CAPITAL = 10000.0
POSITION_SIZE_PCT = 1.0
COMMISSION_PCT = 0.001
SLIPPAGE_PCT = 0.0005

RULE = Rule(entry=ConditionGroup(conditions=[Condition('close', '>', 'sma_20')], logic='and'), exit=None)


def backtest_strategy():
    df = fetch_historical_data(stock, from_date, to_date, timeframe)
    if df.empty:
        return

    result = run_backtest(
        df, RULE,
        initial_capital=INITIAL_CAPITAL,
        position_size_pct=POSITION_SIZE_PCT,
        commission_pct=COMMISSION_PCT,
        slippage_pct=SLIPPAGE_PCT,
    )

    for t in result.trades:
        print(f"BUY  {t.entry_date} @ {t.entry_price:.2f}  ->  SELL {t.exit_date} @ {t.exit_price:.2f}  "
              f"| P&L: {t.pnl:.2f} ({t.return_pct:.2f}%)")

    metrics = compute_metrics(result, df=df)

    print("\n=== Backtest Summary ===")
    print(f"Total trades:      {metrics.num_trades}")
    print(f"Total return:      {metrics.total_return_pct:.2f}%")
    print(f"Win rate:          {metrics.win_rate_pct:.2f}%")
    print(f"Avg trade return:  {metrics.avg_trade_return_pct:.2f}%")
    print(f"Max drawdown:      {metrics.max_drawdown_pct:.2f}%")
    print(f"Sharpe ratio:      {metrics.sharpe_ratio:.2f}")
    print(f"Sortino ratio:     {metrics.sortino_ratio:.2f}")
    print(f"Calmar ratio:      {metrics.calmar_ratio:.2f}")
    print(f"Profit factor:     {metrics.profit_factor:.2f}")
    if metrics.alpha_pct is not None:
        print(f"Alpha vs buy&hold: {metrics.alpha_pct:.2f}%")


if __name__ == "__main__":
    backtest_strategy()
