"""Renders a Rule into a standalone, runnable script.

Every fragment spliced into the generated source comes from
ConditionGroup.render()/Condition.render(), which only ever emit
`row['<allowlisted field>'] <allowlisted operator> <allowlisted field or
number>` (engine.conditions.Condition validates this at construction
time). So even though this is textual code generation, there is no path
from user-typed rule text to arbitrary code in the generated file.
"""
from engine.conditions import Rule

TEMPLATE = '''# generated_strategy.py — auto-generated by agent.py, do not hand-edit.
# Run it from the project root so `data_engine` and `engine` are importable.
"""
Entry rule: {entry_expr}
Exit rule:  {exit_expr}
"""
import pandas as pd

from data_engine import fetch_historical_data
from engine.backtest import BacktestResult, Trade
from engine.indicators import compute_indicators
from engine.metrics import compute_metrics

stock = input("Enter stock ticker (e.g., AAPL, NVDA, SPY): ").strip().upper()
from_date = input("Enter start date (YYYY-MM-DD): ").strip()
to_date = input("Enter end date (YYYY-MM-DD): ").strip()
timeframe = input("Enter timeframe (e.g., 1d for daily, 1h for hourly): ").strip()

INITIAL_CAPITAL = {initial_capital}
POSITION_SIZE_PCT = {position_size_pct}
INDICATORS = {indicators!r}


def backtest_strategy():
    df = fetch_historical_data(stock, from_date, to_date, timeframe)
    if df.empty:
        return
    df = compute_indicators(df, INDICATORS)

    cash = INITIAL_CAPITAL
    shares = 0.0
    entry_date = entry_price = None
    trades = []
    equity_curve = []

    for i in range(len(df)):
        row = df.iloc[i]
        in_position = shares > 0

        if not in_position:
            if {entry_expr}:
                allocation = cash * POSITION_SIZE_PCT
                price = row['close']
                if price > 0:
                    shares = allocation / price
                    cash -= shares * price
                    entry_date, entry_price = row['date'], price
                    print(f"BUY SIGNAL at {{row['date']}} | Price: {{price}}")
        else:
            if {exit_expr}:
                price = row['close']
                cash += shares * price
                trades.append(Trade(entry_date, entry_price, row['date'], price, shares))
                print(f"SELL SIGNAL at {{row['date']}} | Price: {{price}}")
                shares = 0.0

        equity_curve.append(cash + shares * row['close'])

    if shares > 0:
        last = df.iloc[-1]
        cash += shares * last['close']
        trades.append(Trade(entry_date, entry_price, last['date'], last['close'], shares))
        equity_curve[-1] = cash

    result = BacktestResult(
        trades=trades,
        equity_curve=pd.Series(equity_curve),
        dates=df['date'],
        initial_capital=INITIAL_CAPITAL,
        final_equity=equity_curve[-1] if equity_curve else INITIAL_CAPITAL,
    )
    metrics = compute_metrics(result)

    print("\\n=== Backtest Summary ===")
    print(f"Total trades: {{metrics.num_trades}}")
    print(f"Total return: {{metrics.total_return_pct:.2f}}%")
    print(f"Win rate: {{metrics.win_rate_pct:.2f}}%")
    print(f"Avg trade return: {{metrics.avg_trade_return_pct:.2f}}%")
    print(f"Max drawdown: {{metrics.max_drawdown_pct:.2f}}%")
    print(f"Sharpe ratio: {{metrics.sharpe_ratio:.2f}}")


if __name__ == "__main__":
    backtest_strategy()
'''


def generate_script(rule: Rule, initial_capital: float = 10000.0, position_size_pct: float = 1.0) -> str:
    entry_expr = rule.entry.render()
    exit_expr = rule.exit.render() if rule.exit is not None else f"not ({entry_expr})"
    indicators = sorted(rule.indicators_needed())

    return TEMPLATE.format(
        entry_expr=entry_expr,
        exit_expr=exit_expr,
        initial_capital=initial_capital,
        position_size_pct=position_size_pct,
        indicators=indicators,
    )
