"""Renders a Rule into a standalone, runnable script.

Earlier versions of this module reimplemented the backtest loop as a
literal string template, duplicating engine.backtest.run_backtest.
That's a maintenance trap: every change to the real loop (e.g. the
next-bar-execution fix, commission/slippage) would silently NOT be
reflected here unless someone remembered to hand-port it too.

Instead, the generated script reconstructs the exact validated Rule
object as literal constructor calls and calls run_backtest directly —
there is no second loop to keep in sync. This is safe specifically
because Condition/ConditionGroup fields are already validated against
the allowlist at parse time (engine.conditions.Condition.__post_init__);
repr()'ing an already-validated field back into source is not a new
injection surface, since nothing about that value came from an
unvalidated source at this point.
"""
from engine.conditions import Condition, ConditionGroup, Rule

TEMPLATE = '''# generated_strategy.py — auto-generated by agent.py, do not hand-edit.
# Run it from the project root so `data_engine` and `engine` are importable.
"""
Entry rule: {entry_expr}
Exit rule:  {exit_expr}
"""
from data_engine import fetch_historical_data
from engine.backtest import run_backtest
from engine.conditions import Condition, ConditionGroup, Rule
from engine.metrics import compute_metrics

stock = input("Enter stock ticker (e.g., AAPL, NVDA, SPY): ").strip().upper()
from_date = input("Enter start date (YYYY-MM-DD): ").strip()
to_date = input("Enter end date (YYYY-MM-DD): ").strip()
timeframe = input("Enter timeframe (e.g., 1d for daily, 1h for hourly): ").strip()

INITIAL_CAPITAL = {initial_capital!r}
POSITION_SIZE_PCT = {position_size_pct!r}
COMMISSION_PCT = {commission_pct!r}
SLIPPAGE_PCT = {slippage_pct!r}

RULE = {rule_literal}


def backtest_strategy():
    df = fetch_historical_data(stock, from_date, to_date, timeframe)
    if df.empty:
        return

    result = run_backtest(
        df, RULE,
        initial_capital=INITIAL_CAPITAL,
        position_size_pct=POSITION_SIZE_PCT,
        commission_pct=COMMISSION_PCT,
        slippage_pct=SLIPPAGE_PCT,
    )

    for t in result.trades:
        print(f"BUY  {{t.entry_date}} @ {{t.entry_price:.2f}}  ->  SELL {{t.exit_date}} @ {{t.exit_price:.2f}}  "
              f"| P&L: {{t.pnl:.2f}} ({{t.return_pct:.2f}}%)")

    metrics = compute_metrics(result, df=df)

    print("\\n=== Backtest Summary ===")
    print(f"Total trades:      {{metrics.num_trades}}")
    print(f"Total return:      {{metrics.total_return_pct:.2f}}%")
    print(f"Win rate:          {{metrics.win_rate_pct:.2f}}%")
    print(f"Avg trade return:  {{metrics.avg_trade_return_pct:.2f}}%")
    print(f"Max drawdown:      {{metrics.max_drawdown_pct:.2f}}%")
    print(f"Sharpe ratio:      {{metrics.sharpe_ratio:.2f}}")
    print(f"Sortino ratio:     {{metrics.sortino_ratio:.2f}}")
    print(f"Calmar ratio:      {{metrics.calmar_ratio:.2f}}")
    print(f"Profit factor:     {{metrics.profit_factor:.2f}}")
    if metrics.alpha_pct is not None:
        print(f"Alpha vs buy&hold: {{metrics.alpha_pct:.2f}}%")


if __name__ == "__main__":
    backtest_strategy()
'''


def _render_condition_literal(c: Condition) -> str:
    return f"Condition({c.left!r}, {c.operator!r}, {c.right!r})"


def _render_group_literal(group: ConditionGroup) -> str:
    conditions = ", ".join(_render_condition_literal(c) for c in group.conditions)
    return f"ConditionGroup(conditions=[{conditions}], logic={group.logic!r})"


def generate_script(
    rule: Rule,
    initial_capital: float = 10000.0,
    position_size_pct: float = 1.0,
    commission_pct: float = 0.0,
    slippage_pct: float = 0.0,
) -> str:
    entry_expr = rule.entry.render()
    exit_expr = rule.exit.render() if rule.exit is not None else f"not ({entry_expr})"

    exit_literal = _render_group_literal(rule.exit) if rule.exit is not None else "None"
    rule_literal = f"Rule(entry={_render_group_literal(rule.entry)}, exit={exit_literal})"

    return TEMPLATE.format(
        entry_expr=entry_expr,
        exit_expr=exit_expr,
        initial_capital=initial_capital,
        position_size_pct=position_size_pct,
        commission_pct=commission_pct,
        slippage_pct=slippage_pct,
        rule_literal=rule_literal,
    )
